# Generated by Django 5.1.3 on 2024-12-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='isDaytime',
            new_name='is_daytime',
        ),
    ]
