# Generated by Django 5.1.3 on 2024-12-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_rename_isdaytime_reading_is_daytime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='detailedForecast',
            new_name='detailed_forecast',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='shortForecast',
            new_name='short_forecast',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='temperatureUnit',
            new_name='temperature_unit',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='windDirection',
            new_name='wind_direction',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='windSpeed',
            new_name='wind_speed',
        ),
    ]
